/* eslint-disable @typescript-eslint/no-explicit-any */
export interface Word {
    kr: string;
    en: string;
    zh: string;
    pos: string;
    sentenceKr: string;
    sentenceMeaning: string;
    illustrationUrl?: string;
    animationData?: any;
    animationUrl?: string;
}

export const MOCK_VOCABULARY: Record<string, Word[]> = {
    "beginner_cycle_1": [
        { kr: "가게", en: "Store", zh: "商店", pos: "Noun", sentenceKr: "가게에서 우유를 사요.", sentenceMeaning: "I buy milk at the store.", illustrationUrl: "/illustrations/store.png" },
        { kr: "가격", en: "Price", zh: "价格", pos: "Noun", sentenceKr: "이 물건은 가격이 비싸요.", sentenceMeaning: "This item's price is expensive.", illustrationUrl: "/illustrations/price.png" },
        { kr: "가구", en: "Furniture", zh: "家具", pos: "Noun", sentenceKr: "새 집의 가구를 골라요.", sentenceMeaning: "I'm choosing furniture for the new house.", illustrationUrl: "/illustrations/furniture.png" },
        { kr: "가깝다", en: "Near", zh: "近", pos: "Adjective", sentenceKr: "학교가 집에서 아주 가까워요.", sentenceMeaning: "The school is very near the house." },
        { kr: "가끔", en: "Sometimes", zh: "有时", pos: "Adverb", sentenceKr: "가끔 한국 음식을 먹어요.", sentenceMeaning: "I sometimes eat Korean food." },
        { kr: "가난", en: "Poverty", zh: "贫穷", pos: "Noun", sentenceKr: "그는 가난을 이겨냈어요.", sentenceMeaning: "He overcame poverty." },
        { kr: "가늘다", en: "Thin/Slender", zh: "细", pos: "Adjective", sentenceKr: "손가락이 길고 가늘어요.", sentenceMeaning: "The fingers are long and thin." },
        { kr: "가다", en: "To go", zh: "去", pos: "Verb", sentenceKr: "매일 아침 학교에 가요.", sentenceMeaning: "I go to school every morning." },
        { kr: "가득", en: "Full", zh: "满", pos: "Adverb", sentenceKr: "가방에 책이 가득 있어요.", sentenceMeaning: "The bag is full of books." },
        { kr: "가르치다", en: "To teach", zh: "教", pos: "Verb", sentenceKr: "선생님이 한국어를 가르쳐요.", sentenceMeaning: "The teacher teaches Korean." },
        { kr: "가르침", en: "Teaching", zh: "教诲", pos: "Noun", sentenceKr: "선생님의 가르침을 잊지 않아요.", sentenceMeaning: "I don't forget the teacher's teachings." },
        { kr: "가리키다", en: "To point", zh: "指", pos: "Verb", sentenceKr: "손가락으로 저기를 가리켜요.", sentenceMeaning: "I point there with my finger." },
        { kr: "가방", en: "Bag", zh: "包", pos: "Noun", sentenceKr: "예쁜 가방을 샀어요.", sentenceMeaning: "I bought a pretty bag.", illustrationUrl: "/illustrations/bag.png" },
        { kr: "가볍다", en: "Light", zh: "轻", pos: "Adjective", sentenceKr: "이 상자는 아주 가벼워요.", sentenceMeaning: "This box is very light." },
        { kr: "가수", en: "Singer", zh: "歌手", pos: "Noun", sentenceKr: "그는 유명한 가수예요.", sentenceMeaning: "He is a famous singer." },
        { kr: "가슴", en: "Chest/Heart", zh: "胸/心", pos: "Noun", sentenceKr: "가슴이 두근거려요.", sentenceMeaning: "My heart is pounding." },
        { kr: "가요", en: "Song/K-pop", zh: "歌谣", pos: "Noun", sentenceKr: "최신 가요를 들어요.", sentenceMeaning: "I listen to the latest K-pop songs." },
        { kr: "가운데", en: "Middle", zh: "中间", pos: "Noun", sentenceKr: "방 한가운데에 식탁이 있어요.", sentenceMeaning: "There is a dining table in the middle of the room." },
        { kr: "가위", en: "Scissors", zh: "剪刀", pos: "Noun", sentenceKr: "가위로 종이를 잘라요.", sentenceMeaning: "I cut paper with scissors." },
        { kr: "가을", en: "Autumn", zh: "秋天", pos: "Noun", sentenceKr: "가을에는 단풍이 예뻐요.", sentenceMeaning: "The maple leaves are pretty in autumn." },
        { kr: "가장", en: "Most/Best", zh: "最", pos: "Adverb", sentenceKr: "이게 세상에서 가장 맛있어요.", sentenceMeaning: "This is the most delicious thing in the world." },
        { kr: "가져가다", en: "To take", zh: "带走", pos: "Verb", sentenceKr: "우산을 꼭 가져가세요.", sentenceMeaning: "Please make sure to take an umbrella." },
        { kr: "가져오다", en: "To bring", zh: "带来", pos: "Verb", sentenceKr: "숙제를 학교에 가져왔어요.", sentenceMeaning: "I brought my homework to school." },
        { kr: "가족", en: "Family", zh: "家族", pos: "Noun", sentenceKr: "우리 가족은 네 명이에요.", sentenceMeaning: "My family has four people." },
        { kr: "가지", en: "Kind/Sort", zh: "种", pos: "Noun", sentenceKr: "여러 가지 과일이 있어요.", sentenceMeaning: "There are various kinds of fruits." },
        { kr: "가지다", en: "To have", zh: "拥有", pos: "Verb", sentenceKr: "저는 꿈을 가지고 있어요.", sentenceMeaning: "I have a dream." },
        { kr: "가짜", en: "Fake", zh: "假", pos: "Noun", sentenceKr: "그것은 가짜 다이아몬드예요.", sentenceMeaning: "That is a fake diamond." },
        { kr: "가치", en: "Value", zh: "价值", pos: "Noun", sentenceKr: "시간의 가치는 소중해요.", sentenceMeaning: "The value of time is precious." },
        { kr: "각각", en: "Each", zh: "各自", pos: "Adverb", sentenceKr: "학생들에게 각각 선물을 줬어요.", sentenceMeaning: "I gave a gift to each student." },
        { kr: "각오", en: "Determination", zh: "觉悟", pos: "Noun", sentenceKr: "열심히 하겠다는 각오를 했어요.", sentenceMeaning: "I made a determination to work hard." },
        { kr: "각종", en: "Various kinds", zh: "各种", pos: "Noun", sentenceKr: "마트에 각종 채소가 있어요.", sentenceMeaning: "There are various kinds of vegetables at the mart." },
        { kr: "간", en: "Liver", zh: "肝", pos: "Noun", sentenceKr: "술은 간에 좋지 않아요.", sentenceMeaning: "Alcohol is not good for the liver." },
        { kr: "간단하다", en: "Simple", zh: "简单", pos: "Adjective", sentenceKr: "문제가 아주 간단해요.", sentenceMeaning: "The problem is very simple." },
        { kr: "간식", en: "Snack", zh: "零食", pos: "Noun", sentenceKr: "오후에 간식을 먹어요.", sentenceMeaning: "I eat snacks in the afternoon." },
        { kr: "간호사", en: "Nurse", zh: "护士", pos: "Noun", sentenceKr: "병원에서 간호사가 일해요.", sentenceMeaning: "The nurse works at the hospital." },
        { kr: "갈다", en: "To change/grind", zh: "换/磨", pos: "Verb", sentenceKr: "전구를 새로 갈았어요.", sentenceMeaning: "I changed the light bulb." },
        { kr: "갈비", en: "Ribs", zh: "排骨", pos: "Noun", sentenceKr: "저녁에 갈비를 먹었어요.", sentenceMeaning: "I ate ribs for dinner." },
        { kr: "갈비탕", en: "Rib soup", zh: "排骨汤", pos: "Noun", sentenceKr: "따뜻한 갈비탕을 좋아해요.", sentenceMeaning: "I like warm rib soup." },
        { kr: "갈색", en: "Brown", zh: "褐色", pos: "Noun", sentenceKr: "머리색이 갈색이에요.", sentenceMeaning: "The hair color is brown." },
        { kr: "갈아입다", en: "To change clothes", zh: "换衣服", pos: "Verb", sentenceKr: "운동복으로 갈아입어요.", sentenceMeaning: "I change into workout clothes." },
        { kr: "갈아타다", en: "To transfer", zh: "换乘", pos: "Verb", sentenceKr: "강남역에서 2호선으로 갈아타요.", sentenceMeaning: "Transfer to Line 2 at Gangnam Station." },
        { kr: "감", en: "Persimmon", zh: "柿子", pos: "Noun", sentenceKr: "잘 익은 감이 달아요.", sentenceMeaning: "The well-ripened persimmon is sweet." },
        { kr: "감각", en: "Sense", zh: "感觉", pos: "Noun", sentenceKr: "그는 패션 감각이 뛰어나요.", sentenceMeaning: "He has a great sense of fashion." },
        { kr: "감기", en: "Cold (illness)", zh: "感冒", pos: "Noun", sentenceKr: "추워서 감기에 걸렸어요.", sentenceMeaning: "I caught a cold because it was cold." },
        { kr: "감사", en: "Thanks", zh: "感谢", pos: "Noun", sentenceKr: "도와주셔서 감사를 드립니다.", sentenceMeaning: "I give thanks for your help." },
        { kr: "감상", en: "Appreciation", zh: "欣赏", pos: "Noun", sentenceKr: "영화 감상이 취미예요.", sentenceMeaning: "My hobby is watching movies." },
        { kr: "감동", en: "Emotion/Touching", zh: "感动", pos: "Noun", sentenceKr: "그 이야기는 정말 감동이에요.", sentenceMeaning: "That story is truly touching." },
        { kr: "감상하다", en: "To appreciate", zh: "欣赏", pos: "Verb", sentenceKr: "미술관에서 그림을 감상해요.", sentenceMeaning: "I appreciate paintings at the art gallery." },
        { kr: "감정", en: "Feeling/Emotion", zh: "感情", pos: "Noun", sentenceKr: "사람은 다양한 감정이 있어요.", sentenceMeaning: "Humans have various emotions." },
        { kr: "갑자기", en: "Suddenly", zh: "突然", pos: "Adverb", sentenceKr: "비가 갑자기 내리기 시작했어요.", sentenceMeaning: "It suddenly started to rain." },
        { kr: "값", en: "Value/Price", zh: "价格", pos: "Noun", sentenceKr: "물건 값이 너무 올랐어요.", sentenceMeaning: "The price of goods has risen too much." },
        { kr: "강", en: "River", zh: "江", pos: "Noun", sentenceKr: "한강에서 자전거를 타요.", sentenceMeaning: "I ride a bike at the Han River." },
        { kr: "강남", en: "Gangnam", zh: "江南", pos: "Noun", sentenceKr: "강남은 서울에서 번화한 곳이에요.", sentenceMeaning: "Gangnam is a busy place in Seoul." },
        { kr: "강물", en: "River water", zh: "江水", pos: "Noun", sentenceKr: "강물이 맑게 흐르고 있어요.", sentenceMeaning: "The river water is flowing clearly." },
        { kr: "강아지", en: "Puppy", zh: "小狗", pos: "Noun", sentenceKr: "강아지가 꼬리를 흔들어요.", sentenceMeaning: "The puppy is wagging its tail.", illustrationUrl: "/illustrations/puppy.png" },
        { kr: "강요", en: "Coercion", zh: "强迫", pos: "Noun", sentenceKr: "하기 싫은 일을 강요하지 마세요.", sentenceMeaning: "Don't force me to do things I don't want to do." },
        { kr: "강조", en: "Emphasis", zh: "强调", pos: "Noun", sentenceKr: "선생님이 중요한 부분을 강조했어요.", sentenceMeaning: "The teacher emphasized the important part." },
        { kr: "강하다", en: "Strong", zh: "强", pos: "Adjective", sentenceKr: "그는 의지가 아주 강해요.", sentenceMeaning: "He has a very strong will." },
        { kr: "갖다", en: "To have", zh: "持有", pos: "Verb", sentenceKr: "관심을 좀 가져 주세요.", sentenceMeaning: "Please have some interest." },
        { kr: "갖추다", en: "To equip", zh: "具备", pos: "Verb", sentenceKr: "필요한 서류를 다 갖췄어요.", sentenceMeaning: "I have prepared all the necessary documents." },
        { kr: "같다", en: "Same", zh: "相同", pos: "Adjective", sentenceKr: "우리는 생각이 서로 같아요.", sentenceMeaning: "We have the same thoughts." },
        { kr: "같이", en: "Together", zh: "一起", pos: "Adverb", sentenceKr: "우리 같이 점심 먹어요.", sentenceMeaning: "Let's have lunch together." },
        { kr: "갚다", en: "To repay", zh: "偿还", pos: "Verb", sentenceKr: "빌린 돈을 꼭 갚을게요.", sentenceMeaning: "I will definitely repay the borrowed money." },
        { kr: "개", en: "Dog/Counter", zh: "狗/个", pos: "Noun", sentenceKr: "마당에서 개가 짖어요.", sentenceMeaning: "The dog is barking in the yard." },
        { kr: "개관", en: "Opening (facility)", zh: "开馆", pos: "Noun", sentenceKr: "도서관 개관 시간이 언제예요?", sentenceMeaning: "When is the library's opening time?" },
        { kr: "개교", en: "Opening (school)", zh: "开校", pos: "Noun", sentenceKr: "우리 학교는 개교 10주년이에요.", sentenceMeaning: "Our school is having its 10th anniversary of opening." },
        { kr: "개국", en: "Founding a country", zh: "开国", pos: "Noun", sentenceKr: "조선의 개국 과정을 배워요.", sentenceMeaning: "I learn about the founding process of Joseon." },
        { kr: "개나리", en: "Forsythia", zh: "连翘", pos: "Noun", sentenceKr: "봄에는 노란 개나리가 피어요.", sentenceMeaning: "Yellow forsythias bloom in spring." },
        { kr: "개막", en: "Opening (event)", zh: "开幕", pos: "Noun", sentenceKr: "올림픽 개막식이 화려했어요.", sentenceMeaning: "The Olympic opening ceremony was magnificent." },
        { kr: "개발", en: "Development", zh: "开发", pos: "Noun", sentenceKr: "새로운 기술을 개발하고 있어요.", sentenceMeaning: "We are developing new technology." },
        { kr: "개방", en: "Openness", zh: "开放", pos: "Noun", sentenceKr: "이 공원은 24시간 개방이에요.", sentenceMeaning: "This park is open 24 hours." },
        { kr: "개별", en: "Individual", zh: "个别", pos: "Noun", sentenceKr: "개별적으로 상담을 받아요.", sentenceMeaning: "I receive individual counseling." },
        { kr: "개선", en: "Improvement", zh: "改善", pos: "Noun", sentenceKr: "환경 개선이 시급합니다.", sentenceMeaning: "Environmental improvement is urgent." },
        { kr: "개성", en: "Individuality", zh: "个性", pos: "Noun", sentenceKr: "그녀는 개성이 뚜렷해요.", sentenceMeaning: "She has a distinct individuality." },
        { kr: "개업", en: "Opening a business", zh: "开业", pos: "Noun", sentenceKr: "친구의 식당 개업을 축하해요.", sentenceMeaning: "I celebrate the opening of my friend's restaurant." },
        { kr: "개인", en: "Individual", zh: "个人", pos: "Noun", sentenceKr: "이것은 개인적인 일이에요.", sentenceMeaning: "This is a personal matter." },
        { kr: "개정", en: "Revision", zh: "修订", pos: "Noun", sentenceKr: "교과서 개정판이 나왔어요.", sentenceMeaning: "The revised edition of the textbook has come out." },
        { kr: "개최", en: "Hosting (event)", zh: "举办", pos: "Noun", sentenceKr: "서울에서 회담을 개최해요.", sentenceMeaning: "The meeting is held in Seoul." },
        { kr: "개혁", en: "Reform", zh: "改革", pos: "Noun", sentenceKr: "사회의 구조적 개혁이 필요해요.", sentenceMeaning: "Structural reform of society is needed." },
        { kr: "객관적", en: "Objective", zh: "客观的", pos: "Noun", sentenceKr: "객관적인 사실만 말해 주세요.", sentenceMeaning: "Please only tell me objective facts." },
        { kr: "거", en: "Thing/Item", zh: "东西", pos: "Noun", sentenceKr: "이게 내 거니까 건드리지 마.", sentenceMeaning: "This is mine, so don't touch it." },
        { kr: "거기", en: "There", zh: "那里", pos: "Pronoun", sentenceKr: "거기 누구 있어요?", sentenceMeaning: "Is anyone there?" },
        { kr: "거리", en: "Distance/Street", zh: "距离/街道", pos: "Noun", sentenceKr: "집에서 거리가 꽤 멀어요.", sentenceMeaning: "The distance from home is quite far." },
        { kr: "거실", en: "Living room", zh: "客厅", pos: "Noun", sentenceKr: "가족들이 거실에 모여 있어요.", sentenceMeaning: "The family is gathered in the living room." },
        { kr: "거울", en: "Mirror", zh: "镜子", pos: "Noun", sentenceKr: "거울을 보며 화장을 해요.", sentenceMeaning: "I put on makeup while looking in the mirror." },
        { kr: "거의", en: "Almost", zh: "几乎", pos: "Adverb", sentenceKr: "숙제를 거의 다 했어요.", sentenceMeaning: "I have almost finished my homework." },
        { kr: "거짓말", en: "Lie", zh: "谎言", pos: "Noun", sentenceKr: "거짓말을 하면 안 돼요.", sentenceMeaning: "You shouldn't tell lies." },
        { kr: "거절", en: "Refusal", zh: "拒绝", pos: "Noun", sentenceKr: "그는 부탁을 정중히 거절했어요.", sentenceMeaning: "He politely refused the request." },
        { kr: "걱정", en: "Worry", zh: "担心", pos: "Noun", sentenceKr: "시험 때문에 걱정이 많아요.", sentenceMeaning: "I have many worries because of the exam." },
        { kr: "건강", en: "Health", zh: "健康", pos: "Noun", sentenceKr: "운동은 건강에 아주 좋아요.", sentenceMeaning: "Exercise is very good for health." },
        { kr: "건너가다", en: "To go across", zh: "穿过/走过去", pos: "Verb", sentenceKr: "횡단보도를 건너가요.", sentenceMeaning: "I walk across the crosswalk." },
        { kr: "건너다", en: "To cross", zh: "穿过", pos: "Verb", sentenceKr: "길을 건널 때는 조심하세요.", sentenceMeaning: "Please be careful when crossing the road." },
        { kr: "건너편", en: "Opposite side", zh: "对面", pos: "Noun", sentenceKr: "학교 건너편에 서점이 있어요.", sentenceMeaning: "There is a bookstore on the opposite side of the school." },
        { kr: "건물", en: "Building", zh: "建筑物", pos: "Noun", sentenceKr: "이 건물은 아주 높아요.", sentenceMeaning: "This building is very tall." },
        { kr: "건설", en: "Construction", zh: "建设", pos: "Noun", sentenceKr: "새로운 아파트를 건설 중이에요.", sentenceMeaning: "A new apartment is under construction." },
        { kr: "걷다", en: "To walk", zh: "走", pos: "Verb", sentenceKr: "날씨가 좋아서 좀 걷고 싶어요.", sentenceMeaning: "I want to walk a bit because the weather is nice." },
        { kr: "걸다", en: "To hang/make a call", zh: "挂/打电话", pos: "Verb", sentenceKr: "벽에 그림을 걸었어요.", sentenceMeaning: "I hung a picture on the wall." },
        { kr: "걸어가다", en: "To walk there", zh: "走过去", pos: "Verb", sentenceKr: "학교까지 걸어갔어요.", sentenceMeaning: "I walked to school." },
        { kr: "걸어오다", en: "To walk here", zh: "走过来", pos: "Verb", sentenceKr: "집까지 걸어왔어요.", sentenceMeaning: "I walked home." },
        { kr: "걸음", en: "Step", zh: "步", pos: "Noun", sentenceKr: "한 걸음씩 천천히 가세요.", sentenceMeaning: "Please go slowly one step at a time." },
        { kr: "검다", en: "Black", zh: "黑", pos: "Adjective", sentenceKr: "밤하늘이 아주 검어요.", sentenceMeaning: "The night sky is very black." },
        { kr: "것", en: "Thing", zh: "东西", pos: "Noun", sentenceKr: "좋은 것이 많이 있어요.", sentenceMeaning: "There are many good things." },
        { kr: "게", en: "Crab/That thing", zh: "蟹/那个", pos: "Noun", sentenceKr: "맛있는 게를 먹었어요.", sentenceMeaning: "I ate delicious crabs." },
        { kr: "게시판", en: "Bulletin board", zh: "布告栏", pos: "Noun", sentenceKr: "게시판의 공지사항을 확인하세요.", sentenceMeaning: "Please check the announcements on the bulletin board." },
        { kr: "게으르다", en: "Lazy", zh: "懒惰", pos: "Adjective", sentenceKr: "그는 조금 게으른 편이에요.", sentenceMeaning: "He is on the lazy side." },
        { kr: "겨울", en: "Winter", zh: "冬天", pos: "Noun", sentenceKr: "겨울에는 눈이 와요.", sentenceMeaning: "It snows in winter." },
        { kr: "결과", en: "Result", zh: "结果", pos: "Noun", sentenceKr: "시험 결과가 나왔어요.", sentenceMeaning: "The exam results came out." }
    ],
    "beginner_cycle_2": [
        { kr: "결심", en: "Resolution", zh: "决心", pos: "Noun", sentenceKr: "새해 결심을 했어요.", sentenceMeaning: "I made a New Year's resolution." },
        { kr: "결정", en: "Decision", zh: "决定", pos: "Noun", sentenceKr: "아직 결정을 못 했어요.", sentenceMeaning: "I haven't made a decision yet." },
        { kr: "결혼", en: "Marriage", zh: "结婚", pos: "Noun", sentenceKr: "두 사람은 결혼을 약속했어요.", sentenceMeaning: "The two promised to marry." },
        { kr: "결혼식", en: "Wedding", zh: "婚礼", pos: "Noun", sentenceKr: "내일 친구 결혼식에 가요.", sentenceMeaning: "I am going to a friend's wedding tomorrow." },
        { kr: "겸손", en: "Humility", zh: "谦虚", pos: "Noun", sentenceKr: "그는 항상 겸손하게 말해요.", sentenceMeaning: "He always speaks humbly." },
        { kr: "경고", en: "Warning", zh: "警告", pos: "Noun", sentenceKr: "심판이 선수에게 경고를 줬어요.", sentenceMeaning: "The referee gave a warning to the player." },
        { kr: "경기", en: "Game/Economy", zh: "竞技/经济", pos: "Noun", sentenceKr: "축구 경기를 구경해요.", sentenceMeaning: "I watch a soccer game." },
        { kr: "경과", en: "Progress/Passage", zh: "经过", pos: "Noun", sentenceKr: "시간의 경과를 지켜봐요.", sentenceMeaning: "I watch the passage of time." },
        { kr: "경기장", en: "Stadium", zh: "竞技场", pos: "Noun", sentenceKr: "경기장에 관중이 많아요.", sentenceMeaning: "There are many spectators in the stadium." },
        { kr: "경력", en: "Career", zh: "经历", pos: "Noun", sentenceKr: "업무 경력이 화려해요.", sentenceMeaning: "The work career is impressive." },
        { kr: "경비", en: "Cost/Security", zh: "经费/警备", pos: "Noun", sentenceKr: "여행 경비가 많이 들어요.", sentenceMeaning: "The travel expenses are high." },
        { kr: "경영", en: "Management", zh: "经营", pos: "Noun", sentenceKr: "회사 경영이 어려워졌어요.", sentenceMeaning: "Company management has become difficult." },
        { kr: "경우", en: "Case/Situation", zh: "情况", pos: "Noun", sentenceKr: "비가 올 경우에 대비해요.", sentenceMeaning: "Prepare for the case it rains." },
        { kr: "경제", en: "Economy", zh: "经济", pos: "Noun", sentenceKr: "한국 경제에 대해 공부해요.", sentenceMeaning: "I study about the Korean economy." },
        { kr: "경찰", en: "Police", zh: "警察", pos: "Noun", sentenceKr: "길을 잃어서 경찰에게 물어봤어요.", sentenceMeaning: "I got lost and asked the police." },
        { kr: "경찰관", en: "Police officer", zh: "警官", pos: "Noun", sentenceKr: "경찰관이 교통 정리를 해요.", sentenceMeaning: "The police officer organizes traffic." },
        { kr: "경찰서", en: "Police station", zh: "警察署", pos: "Noun", sentenceKr: "경찰서에 신고를 했어요.", sentenceMeaning: "I reported to the police station." },
        { kr: "경치", en: "Scenery", zh: "景色", pos: "Noun", sentenceKr: "여기는 경치가 정말 좋아요.", sentenceMeaning: "The scenery here is really good." },
        { kr: "경험", en: "Experience", zh: "经验", pos: "Noun", sentenceKr: "다양한 경험을 하고 싶어요.", sentenceMeaning: "I want to have various experiences." },
        { kr: "계단", en: "Stairs", zh: "楼梯", pos: "Noun", sentenceKr: "계단을 조심히 올라가세요.", sentenceMeaning: "Please go up the stairs carefully." },
        { kr: "계란", en: "Egg", zh: "鸡蛋", pos: "Noun", sentenceKr: "아침에 계란을 먹어요.", sentenceMeaning: "I eat eggs in the morning." },
        { kr: "계산", en: "Calculation", zh: "计算", pos: "Noun", sentenceKr: "식사 후에 계산을 했어요.", sentenceMeaning: "I paid after the meal." },
        { kr: "계속", en: "Continuous", zh: "继续", pos: "Adverb", sentenceKr: "공부를 계속 하고 있어요.", sentenceMeaning: "I am continuing to study." },
        { kr: "계시다", en: "To be (Honorific)", zh: "在", pos: "Verb", sentenceKr: "선생님은 집에 계세요.", sentenceMeaning: "The teacher is at home." },
        { kr: "계절", en: "Season", zh: "季节", pos: "Noun", sentenceKr: "좋아하는 계절이 뭐예요?", sentenceMeaning: "What is your favorite season?" },
        { kr: "계획", en: "Plan", zh: "计划", pos: "Noun", sentenceKr: "방학 계획을 세웠어요.", sentenceMeaning: "I made vacation plans." },
        { kr: "고기", en: "Meat", zh: "肉", pos: "Noun", sentenceKr: "저녁에 고기를 구워 먹어요.", sentenceMeaning: "We'll grill and eat meat for dinner." },
        { kr: "고등학교", en: "High school", zh: "高中", pos: "Noun", sentenceKr: "동생은 고등학교 1학년이에요.", sentenceMeaning: "My younger sibling is a high school freshman." },
        { kr: "고맙다", en: "Thankful", zh: "谢谢", pos: "Adjective", sentenceKr: "도와주셔서 정말 고마워요.", sentenceMeaning: "Thank you very much for your help." },
        { kr: "고양이", en: "Cat", zh: "猫", pos: "Noun", sentenceKr: "귀여운 고양이가 잠을 자요.", sentenceMeaning: "A cute cat is sleeping.", illustrationUrl: "/illustrations/cat.png" },
        { kr: "고생", en: "Hardship", zh: "辛苦", pos: "Noun", sentenceKr: "그동안 고생 많으셨습니다.", sentenceMeaning: "You've worked very hard." },
        { kr: "고치다", en: "To repair", zh: "修理", pos: "Verb", sentenceKr: "고장 난 시계를 고쳤어요.", sentenceMeaning: "I fixed the broken watch." },
        { kr: "고향", en: "Hometown", zh: "故乡", pos: "Noun", sentenceKr: "고향에 계신 부모님이 보고 싶어요.", sentenceMeaning: "I miss my parents in my hometown." },
        { kr: "곧", en: "Soon", zh: "马上", pos: "Adverb", sentenceKr: "곧 도착할 예정입니다.", sentenceMeaning: "I am scheduled to arrive soon." },
        { kr: "골목", en: "Alley", zh: "胡同", pos: "Noun", sentenceKr: "좁은 골목을 지나갔어요.", sentenceMeaning: "I passed through a narrow alley." },
        { kr: "곱다", en: "Pretty/Soft", zh: "美/软", pos: "Adjective", sentenceKr: "피부가 아주 곱네요.", sentenceMeaning: "The skin is very soft and pretty." },
        { kr: "곳", en: "Place", zh: "地方", pos: "Noun", sentenceKr: "이곳은 조용한 곳이에요.", sentenceMeaning: "This is a quiet place." },
        { kr: "공무원", en: "Public official", zh: "公务员", pos: "Noun", sentenceKr: "형은 시청 공무원이에요.", sentenceMeaning: "My older brother is a city hall official." },
        { kr: "공부", en: "Study", zh: "学习", pos: "Noun", sentenceKr: "한국어 공부가 재미있어요.", sentenceMeaning: "Studying Korean is fun." },
        { kr: "공원", en: "Park", zh: "公园", pos: "Noun", sentenceKr: "공원에서 산책을 해요.", sentenceMeaning: "I take a walk in the park." },
        { kr: "공장", en: "Factory", zh: "工厂", pos: "Noun", sentenceKr: "공장에서 물건을 만들어요.", sentenceMeaning: "They make things in the factory." },
        { kr: "공중전화", en: "Public phone", zh: "公用电话", pos: "Noun", sentenceKr: "요즘은 공중전화가 별로 없어요.", sentenceMeaning: "There aren't many public phones these days." },
        { kr: "공항", en: "Airport", zh: "机场", pos: "Noun", sentenceKr: "비행기를 타러 공항에 가요.", sentenceMeaning: "I go to the airport to take a flight." },
        { kr: "과거", en: "Past", zh: "过去", pos: "Noun", sentenceKr: "과거를 잊고 미래를 봐요.", sentenceMeaning: "Forget the past and look at the future." },
        { kr: "과일", en: "Fruit", zh: "水果", pos: "Noun", sentenceKr: "식후에 과일을 먹어요.", sentenceMeaning: "Eat fruit after a meal." },
        { kr: "과자", en: "Snack", zh: "点心", pos: "Noun", sentenceKr: "아이들이 과자를 좋아해요.", sentenceMeaning: "Children like snacks." },
        { kr: "관심", en: "Interest", zh: "关心", pos: "Noun", sentenceKr: "한국 문화에 관심이 많아요.", sentenceMeaning: "I have a lot of interest in Korean culture." },
        { kr: "광고", en: "Advertisement", zh: "广告", pos: "Noun", sentenceKr: "TV 광고가 재미있어요.", sentenceMeaning: "The TV ad is funny." },
        { kr: "괜찮다", en: "Okay", zh: "没关系", pos: "Adjective", sentenceKr: "저는 정말 괜찮아요.", sentenceMeaning: "I am really okay." },
        { kr: "괴로움", en: "Suffering", zh: "痛苦", pos: "Noun", sentenceKr: "괴로움을 참고 견뎠어요.", sentenceMeaning: "I endured the suffering." },
        { kr: "교실", en: "Classroom", zh: "教室", pos: "Noun", sentenceKr: "교실에 학생들이 모였어요.", sentenceMeaning: "Students gathered in the classroom." },
        { kr: "교수", en: "Professor", zh: "教授", pos: "Noun", sentenceKr: "교수님이 강의를 하세요.", sentenceMeaning: "The professor is lecturing." },
        { kr: "교통", en: "Traffic", zh: "交通", pos: "Noun", sentenceKr: "교통이 매우 복잡해요.", sentenceMeaning: "The traffic is very complicated." },
        { kr: "교통사고", en: "Traffic accident", zh: "交通事故", pos: "Noun", sentenceKr: "사거리에 교통사고가 났어요.", sentenceMeaning: "There was a traffic accident at the intersection." },
        { kr: "교회", en: "Church", zh: "教会", pos: "Noun", sentenceKr: "일요일에 교회에 가요.", sentenceMeaning: "I go to church on Sunday." },
        { kr: "구경", en: "Sightseeing", zh: "观光", pos: "Noun", sentenceKr: "동대문 시장 구경을 갔어요.", sentenceMeaning: "I went sightseeing at Dongdaemun Market." },
        { kr: "구두", en: "Shoes", zh: "皮鞋", pos: "Noun", sentenceKr: "새 구두를 신었어요.", sentenceMeaning: "I put on new shoes." },
        { kr: "구름", en: "Cloud", zh: "云", pos: "Noun", sentenceKr: "하늘에 구름이 많아요.", sentenceMeaning: "There are many clouds in the sky." },
        { kr: "구십", en: "90", zh: "九十", pos: "Number", sentenceKr: "할머니는 구십 세이십니다.", sentenceMeaning: "My grandmother is 90 years old." },
        { kr: "구월", en: "September", zh: "九月", pos: "Noun", sentenceKr: "구월은 가을의 시작이에요.", sentenceMeaning: "September is the start of autumn." },
        { kr: "구하다", en: "To find/Save", zh: "寻找/求救", pos: "Verb", sentenceKr: "도움을 줄 사람을 구해요.", sentenceMeaning: "I'm looking for someone to help." },
        { kr: "국", en: "Soup", zh: "汤", pos: "Noun", sentenceKr: "밥과 국을 같이 먹어요.", sentenceMeaning: "Eat rice and soup together." },
        { kr: "국가", en: "Country", zh: "国家", pos: "Noun", sentenceKr: "국가의 미래를 생각해요.", sentenceMeaning: "Think about the future of the country." },
        { kr: "국내", en: "Domestic", zh: "国内", pos: "Noun", sentenceKr: "국내 여행을 떠나요.", sentenceMeaning: "I am going on a domestic trip." },
        { kr: "국수", en: "Noodles", zh: "面条", pos: "Noun", sentenceKr: "점심으로 국수를 먹었어요.", sentenceMeaning: "I ate noodles for lunch." },
        { kr: "국어", en: "National language", zh: "国语", pos: "Noun", sentenceKr: "국어 시간에 시를 배웠어요.", sentenceMeaning: "I learned poetry in Korean class." },
        { kr: "국제", en: "International", zh: "国际", pos: "Noun", sentenceKr: "국제 공항에 사람이 많아요.", sentenceMeaning: "There are many people at the international airport." },
        { kr: "군인", en: "Soldier", zh: "军人", pos: "Noun", sentenceKr: "군인이 나라를 지켜요.", sentenceMeaning: "Soldiers protect the country." },
        { kr: "굽다", en: "To roast/bake", zh: "烤", pos: "Verb", sentenceKr: "오븐에 빵을 구워요.", sentenceMeaning: "I bake bread in the oven." },
        { kr: "권", en: "Volume (book counter)", zh: "卷/本", pos: "Counter", sentenceKr: "책 세 권을 읽었어요.", sentenceMeaning: "I read three books." },
        { kr: "귀", en: "Ear", zh: "耳", pos: "Noun", sentenceKr: "토끼 귀는 아주 길어요.", sentenceMeaning: "Rabbit ears are very long." },
        { kr: "귀엽다", en: "Cute", zh: "可爱", pos: "Adjective", sentenceKr: "아기가 정말 귀엽네요.", sentenceMeaning: "The baby is really cute." },
        { kr: "규칙", en: "Rule", zh: "规则", pos: "Noun", sentenceKr: "교통 규칙을 지켜야 해요.", sentenceMeaning: "You must follow traffic rules." },
        { kr: "귤", en: "Tangerine", zh: "橘子", pos: "Noun", sentenceKr: "겨울에 귤을 많이 먹어요.", sentenceMeaning: "I eat many tangerines in winter." },
        { kr: "그", en: "He/That", zh: "他/那个", pos: "Pronoun", sentenceKr: "그 사람은 내 친구예요.", sentenceMeaning: "That person is my friend." },
        { kr: "그것", en: "That thing", zh: "那个", pos: "Pronoun", sentenceKr: "그것은 아주 중요해요.", sentenceMeaning: "That is very important." },
        { kr: "그곳", en: "That place", zh: "那个地方", pos: "Pronoun", sentenceKr: "그곳에 다시 가고 싶어요.", sentenceMeaning: "I want to go to that place again." },
        { kr: "그날", en: "That day", zh: "那天", pos: "Noun", sentenceKr: "그날 우리는 정말 즐거웠어요.", sentenceMeaning: "We were really happy that day." },
        { kr: "그냥", en: "Just", zh: "就这样", pos: "Adverb", sentenceKr: "그냥 여기 있을게요.", sentenceMeaning: "I'll just stay here." },
        { kr: "그대", en: "You", zh: "你", pos: "Pronoun", sentenceKr: "내 마음은 그대에게 있어요.", sentenceMeaning: "My heart is with you." },
        { kr: "그대로", en: "As it is", zh: "照原样", pos: "Adverb", sentenceKr: "있는 그대로 보여 주세요.", sentenceMeaning: "Please show it as it is." },
        { kr: "그동안", en: "During that time", zh: "这段时间", pos: "Noun", sentenceKr: "그동안 잘 지냈어요?", sentenceMeaning: "Have you been doing well during that time?" },
        { kr: "그때", en: "That time", zh: "那时候", pos: "Noun", sentenceKr: "그때가 기억나네요.", sentenceMeaning: "I remember that time." },
        { kr: "그래", en: "Yes/So", zh: "是/就这样", pos: "Adverb", sentenceKr: "그래, 내가 할게.", sentenceMeaning: "Okay, I'll do it." },
        { kr: "그래서", en: "So", zh: "所以", pos: "Adverb", sentenceKr: "늦었어요, 그래서 뛰었어요.", sentenceMeaning: "I was late, so I ran." },
        { kr: "그러니까", en: "Therefore", zh: "所以", pos: "Adverb", sentenceKr: "공부해, 그러니까 좋은 점수를 받지.", sentenceMeaning: "Study, that's why you get good grades." },
        { kr: "그러면", en: "If so/Then", zh: "那么", pos: "Adverb", sentenceKr: "안 되면 그러면 어떡하지?", sentenceMeaning: "If it doesn't work, then what should we do?" },
        { kr: "그러므로", en: "Therefore", zh: "因此", pos: "Adverb", sentenceKr: "그는 아프다, 그러므로 쉰다.", sentenceMeaning: "He is sick, therefore he rests." },
        { kr: "그런", en: "Such/That kind of", zh: "那种", pos: "Determiner", sentenceKr: "그런 말은 하지 마세요.", sentenceMeaning: "Please don't say such things." },
        { kr: "그런데", en: "But/By the way", zh: "但是", pos: "Adverb", sentenceKr: "공부했어요. 그런데 성적이 낮아요.", sentenceMeaning: "I studied. But the grades are low." },
        { kr: "그렇게", en: "Like that", zh: "那样", pos: "Adverb", sentenceKr: "그렇게 하는 게 맞아요.", sentenceMeaning: "It's right to do it like that." },
        { kr: "그렇다", en: "To be so", zh: "是那样", pos: "Adjective", sentenceKr: "정말 그렇습니까?", sentenceMeaning: "Is that really so?" },
        { kr: "그렇지만", en: "But/However", zh: "但是", pos: "Adverb", sentenceKr: "피곤해요. 그렇지만 일을 해요.", sentenceMeaning: "I'm tired. However, I'm working." },
        { kr: "그릇", en: "Bowl/Dish", zh: "碗", pos: "Noun", sentenceKr: "그릇에 음식을 담아요.", sentenceMeaning: "Put food in the bowl." },
        { kr: "그리", en: "So/Very", zh: "那么", pos: "Adverb", sentenceKr: "그리 멀지 않아요.", sentenceMeaning: "It's not that far." },
        { kr: "그리고", en: "And", zh: "和/然后", pos: "Adverb", sentenceKr: "빵 그리고 우유를 샀어요.", sentenceMeaning: "I bought bread and milk." },
        { kr: "그리다", en: "To draw", zh: "画", pos: "Verb", sentenceKr: "도화지에 그림을 그려요.", sentenceMeaning: "I draw a picture on the paper." },
        { kr: "그립다", en: "To miss", zh: "想念", pos: "Adjective", sentenceKr: "가족이 너무 그리워요.", sentenceMeaning: "I miss my family so much." },
        { kr: "그만", en: "Stop/That's enough", zh: "停止", pos: "Adverb", sentenceKr: "이제 그만 하세요.", sentenceMeaning: "Please stop now." },
        { kr: "그만두다", en: "To quit", zh: "辞去/放弃", pos: "Verb", sentenceKr: "회사를 그만두기로 했어요.", sentenceMeaning: "I decided to quit the company." }
    ],
    "beginner_cycle_3": [
        { kr: "그분", en: "That person (formal)", zh: "那位", pos: "Pronoun", sentenceKr: "그분은 우리 선생님이세요.", sentenceMeaning: "That person is our teacher.", illustrationUrl: "/illustrations/person.png" },
        { kr: "그저께", en: "Day before yesterday", zh: "前天", pos: "Adverb/Noun", sentenceKr: "그저께 밤에 도착했어요.", sentenceMeaning: "I arrived the night before yesterday." },
        { kr: "그쪽", en: "That side/way", zh: "那边", pos: "Pronoun", sentenceKr: "그쪽으로 가세요.", sentenceMeaning: "Please go that way." },
        { kr: "그치다", en: "To stop", zh: "停止", pos: "Verb", sentenceKr: "비가 곧 그칠 거예요.", sentenceMeaning: "The rain will stop soon." },
        { kr: "극장", en: "Theater", zh: "剧场", pos: "Noun", sentenceKr: "극장에서 영화를 봐요.", sentenceMeaning: "I watch a movie at the theater." },
        { kr: "근처", en: "Vicinity/Near", zh: "附近", pos: "Noun", sentenceKr: "집 근처에 공원이 있어요.", sentenceMeaning: "There is a park near my house." },
        { kr: "글", en: "Writing/Text", zh: "文章", pos: "Noun", sentenceKr: "글을 쓰다.", sentenceMeaning: "Write a text." },
        { kr: "글쎄", en: "Well...", zh: "这个嘛", pos: "Interjection", sentenceKr: "글쎄, 잘 모르겠어요.", sentenceMeaning: "Well, I don't really know." },
        { kr: "글쎄요", en: "Well... (Polite)", zh: "这个嘛", pos: "Interjection", sentenceKr: "글쎄요, 잘 모르겠네요.", sentenceMeaning: "Well, I'm not sure." },
        { kr: "금방", en: "Soon/Just now", zh: "马上", pos: "Adverb", sentenceKr: "금방 돌아올게요.", sentenceMeaning: "I'll be back soon." },
        { kr: "금요일", en: "Friday", zh: "星期五", pos: "Noun", sentenceKr: "금요일에 만나요.", sentenceMeaning: "Let's meet on Friday." },
        { kr: "금지", en: "Prohibition", zh: "禁止", pos: "Noun", sentenceKr: "이곳은 주차 금지예요.", sentenceMeaning: "Parking is prohibited here." },
        { kr: "급하다", en: "To be urgent", zh: "急", pos: "Adjective", sentenceKr: "사정이 급해요.", sentenceMeaning: "The circumstances are urgent." },
        { kr: "기간", en: "Period/Duration", zh: "期间", pos: "Noun", sentenceKr: "기간이 지났어요.", sentenceMeaning: "The period has passed." },
        { kr: "기다리다", en: "To wait", zh: "等", pos: "Verb", sentenceKr: "친구를 기다려요.", sentenceMeaning: "I wait for my friend." },
        { kr: "기르다", en: "To raise/grow", zh: "养", pos: "Verb", sentenceKr: "강아지를 길러요.", sentenceMeaning: "I raise a puppy." },
        { kr: "기름", en: "Oil", zh: "油", pos: "Noun", sentenceKr: "기름에 튀겨요.", sentenceMeaning: "Fry in oil." },
        { kr: "기말시험", en: "Final exam", zh: "期末考试", pos: "Noun", sentenceKr: "기말시험을 봐요.", sentenceMeaning: "Take the final exam." },
        { kr: "기분", en: "Mood/Feeling", zh: "心情", pos: "Noun", sentenceKr: "오늘 기분이 좋아요.", sentenceMeaning: "I feel good today." },
        { kr: "기뻐하다", en: "To be happy", zh: "高兴", pos: "Verb", sentenceKr: "졸업을 기뻐해요.", sentenceMeaning: "Be happy about graduation." },
        { kr: "기쁘다", en: "To be happy/glad", zh: "开心", pos: "Adjective", sentenceKr: "마음이 정말 기뻐요.", sentenceMeaning: "I am truly happy." },
        { kr: "기쁨", en: "Joy/Happiness", zh: "喜悦", pos: "Noun", sentenceKr: "기쁨을 나눠요.", sentenceMeaning: "Share the joy." },
        { kr: "기숙사", en: "Dormitory", zh: "宿舍", pos: "Noun", sentenceKr: "기숙사에서 살아요.", sentenceMeaning: "I live in a dormitory." },
        { kr: "기억", en: "Memory", zh: "记忆", pos: "Noun", sentenceKr: "기억이 나지 않아요.", sentenceMeaning: "I don't remember." },
        { kr: "기억나다", en: "To remember", zh: "想起", pos: "Verb", sentenceKr: "이름이 기억나요.", sentenceMeaning: "I remember the name." },
        { kr: "기온", en: "Temperature", zh: "气温", pos: "Noun", sentenceKr: "기온이 높아요.", sentenceMeaning: "The temperature is high." },
        { kr: "기자", en: "Reporter/Journalist", zh: "记者", pos: "Noun", sentenceKr: "신문 기자예요.", sentenceMeaning: "I am a newspaper reporter." },
        { kr: "기차", en: "Train", zh: "火车", pos: "Noun", sentenceKr: "기차를 타요.", sentenceMeaning: "Take a train." },
        { kr: "기차역", en: "Train station", zh: "火车站", pos: "Noun", sentenceKr: "기차역에 도착했어요.", sentenceMeaning: "Arrived at the train station." },
        { kr: "기차표", en: "Train ticket", zh: "火车票", pos: "Noun", sentenceKr: "기차표를 끊어요.", sentenceMeaning: "Buy a train ticket." },
        { kr: "기침", en: "Cough", zh: "咳嗽", pos: "Noun", sentenceKr: "기침이 나요.", sentenceMeaning: "I have a cough." },
        { kr: "기타", en: "Guitar", zh: "吉他", pos: "Noun", sentenceKr: "기타를 쳐요.", sentenceMeaning: "Play the guitar." },
        { kr: "기회", en: "Opportunity", zh: "机会", pos: "Noun", sentenceKr: "기회를 놓쳤어요.", sentenceMeaning: "I missed the opportunity." },
        { kr: "긴장", en: "Nervousness/Tension", zh: "紧张", pos: "Noun", sentenceKr: "긴장을 풀어요.", sentenceMeaning: "Relax the tension." },
        { kr: "길", en: "Road/Way", zh: "路", pos: "Noun", sentenceKr: "길이 막혀요.", sentenceMeaning: "The road is blocked." },
        { kr: "길다", en: "To be long", zh: "长", pos: "Adjective", sentenceKr: "다리가 길어요.", sentenceMeaning: "Legs are long." },
        { kr: "길이", en: "Length", zh: "长度", pos: "Noun", sentenceKr: "길이를 재요.", sentenceMeaning: "Measure the length." },
        { kr: "깊다", en: "To be deep", zh: "深", pos: "Adjective", sentenceKr: "바다가 깊어요.", sentenceMeaning: "The sea is deep." },
        { kr: "김밥", en: "Kimbap", zh: "紫菜包饭", pos: "Noun", sentenceKr: "김밥을 싸요.", sentenceMeaning: "Pack kimbap." },
        { kr: "김치", en: "Kimchi", zh: "泡菜", pos: "Noun", sentenceKr: "김치를 담가요.", sentenceMeaning: "Make kimchi." },
        { kr: "김치찌개", en: "Kimchi stew", zh: "泡菜锅", pos: "Noun", sentenceKr: "김치찌개를 끓여요.", sentenceMeaning: "Boil kimchi stew." },
        { kr: "깨끗하다", en: "To be clean", zh: "干净", pos: "Adjective", sentenceKr: "방이 깨끗해요.", sentenceMeaning: "The room is clean." },
        { kr: "깨끗이", en: "Cleanly", zh: "干净地", pos: "Adverb", sentenceKr: "깨끗이 씻어요.", sentenceMeaning: "Wash cleanly." },
        { kr: "꺼내다", en: "To take out", zh: "拿出", pos: "Verb", sentenceKr: "지갑에서 돈을 꺼내요.", sentenceMeaning: "Take out money from the wallet." },
        { kr: "껌", en: "Gum", zh: "口香糖", pos: "Noun", sentenceKr: "껌을 씹어요.", sentenceMeaning: "Chew gum." },
        { kr: "꼭", en: "Surely/Definitely", zh: "一定", pos: "Adverb", sentenceKr: "꼭 약속할게요.", sentenceMeaning: "I will definitely promise." },
        { kr: "꽃", en: "Flower", zh: "花", pos: "Noun", sentenceKr: "꽃이 피었어요.", sentenceMeaning: "The flower has bloomed." },
        { kr: "꽃가게", en: "Flower shop", zh: "花店", pos: "Noun", sentenceKr: "꽃가게를 방문해요.", sentenceMeaning: "Visit a flower shop." },
        { kr: "꽃병", en: "Flower vase", zh: "花瓶", pos: "Noun", sentenceKr: "꽃병이 예뻐요.", sentenceMeaning: "The flower vase is pretty." },
        { kr: "꽃집", en: "Flower shop", zh: "花店", pos: "Noun", sentenceKr: "꽃집을 열어요.", sentenceMeaning: "Open a flower shop." },
        { kr: "꾸다", en: "To dream", zh: "做梦", pos: "Verb", sentenceKr: "꿈을 꿔요.", sentenceMeaning: "Dream a dream." },
        { kr: "꾸미다", en: "To decorate", zh: "装饰", pos: "Verb", sentenceKr: "방을 예쁘게 꾸며요.", sentenceMeaning: "Decorate the room prettily." },
        { kr: "끄다", en: "To turn off", zh: "关/熄灭", pos: "Verb", sentenceKr: "불을 꺼요.", sentenceMeaning: "Turn off the light." },
        { kr: "끊다", en: "To cut/quit", zh: "切断/戒掉", pos: "Verb", sentenceKr: "담배를 끊었어요.", sentenceMeaning: "I quit smoking." },
        { kr: "끓다", en: "To boil", zh: "沸腾", pos: "Verb", sentenceKr: "물이 끓어요.", sentenceMeaning: "The water is boiling." },
        { kr: "끓이다", en: "To boil something", zh: "煮", pos: "Verb", sentenceKr: "라면을 끓여요.", sentenceMeaning: "Boil ramen." },
        { kr: "끝", en: "End", zh: "结束", pos: "Noun", sentenceKr: "끝이 보여요.", sentenceMeaning: "The end is in sight." },
        { kr: "끝나다", en: "To end/finish", zh: "结束", pos: "Verb", sentenceKr: "수업이 끝났어요.", sentenceMeaning: "The class has ended." },
        { kr: "끝내다", en: "To finish", zh: "完成", pos: "Verb", sentenceKr: "숙제를 끝냈어요.", sentenceMeaning: "I finished my homework." },
        { kr: "끼다", en: "To wear (ring/gloves)", zh: "戴", pos: "Verb", sentenceKr: "반지를 껴요.", sentenceMeaning: "Wear a ring." },
        { kr: "나", en: "I/Me", zh: "我", pos: "Pronoun", sentenceKr: "나는 학생이에요.", sentenceMeaning: "I am a student." },
        { kr: "나가다", en: "To go out", zh: "出去", pos: "Verb", sentenceKr: "밖으로 나가요.", sentenceMeaning: "Go outside." },
        { kr: "나누다", en: "To divide/share", zh: "分享", pos: "Verb", sentenceKr: "둘로 나눠요.", sentenceMeaning: "Divide into two." },
        { kr: "나다", en: "To occur", zh: "发生", pos: "Verb", sentenceKr: "소문이 났어요.", sentenceMeaning: "A rumor has spread." },
        { kr: "나라", en: "Country", zh: "国家", pos: "Noun", sentenceKr: "우리 나라는 아름다워요.", sentenceMeaning: "Our country is beautiful." },
        { kr: "나머지", en: "Rest/Remainder", zh: "剩下", pos: "Noun", sentenceKr: "나머지 돈을 주세요.", sentenceMeaning: "Give me the remaining money." },
        { kr: "나무", en: "Tree", zh: "树", pos: "Noun", sentenceKr: "나무를 심어요.", sentenceMeaning: "Plant a tree." },
        { kr: "나쁘다", en: "To be bad", zh: "坏", pos: "Adjective", sentenceKr: "공기가 나빠요.", sentenceMeaning: "The air is bad." },
        { kr: "나오다", en: "To come out", zh: "出来", pos: "Verb", sentenceKr: "밖으로 나와요.", sentenceMeaning: "Come outside." },
        { kr: "나이", en: "Age", zh: "年龄", pos: "Noun", sentenceKr: "나이가 많아요.", sentenceMeaning: "I am old." },
        { kr: "나중", en: "Later", zh: "以后", pos: "Noun", sentenceKr: "나중에 해요.", sentenceMeaning: "Do it later." },
        { kr: "나타나다", en: "To appear", zh: "出现", pos: "Verb", sentenceKr: "건물이 나타났어요.", sentenceMeaning: "A building appeared." },
        { kr: "나흘", en: "Four days", zh: "四天", pos: "Noun", sentenceKr: "나흘이 걸려요.", sentenceMeaning: "It takes four days." },
        { kr: "낚시", en: "Fishing", zh: "钓鱼", pos: "Noun", sentenceKr: "낚시를 하러 가요.", sentenceMeaning: "Go fishing." },
        { kr: "날", en: "Day", zh: "日子", pos: "Noun", sentenceKr: "마지막 날이에요.", sentenceMeaning: "It is the last day." },
        { kr: "날다", en: "To fly", zh: "飞", pos: "Verb", sentenceKr: "새가 날아요.", sentenceMeaning: "A bird flies." },
        { kr: "날씨", en: "Weather", zh: "天气", pos: "Noun", sentenceKr: "날씨가 좋아요.", sentenceMeaning: "The weather is good." },
        { kr: "날씬하다", en: "To be slim", zh: "苗条", pos: "Adjective", sentenceKr: "몸매가 날씬해요.", sentenceMeaning: "The body is slim." },
        { kr: "날아다니다", en: "To fly around", zh: "飞来飞去", pos: "Verb", sentenceKr: "나비가 날아다녀요.", sentenceMeaning: "A butterfly is flying around." },
        { kr: "날짜", en: "Date", zh: "日期", pos: "Noun", sentenceKr: "날짜를 정해요.", sentenceMeaning: "Set a date." },
        { kr: "남", en: "Others", zh: "别人", pos: "Noun", sentenceKr: "남을 도와줘요.", sentenceMeaning: "Help others." },
        { kr: "남기다", en: "To leave behind", zh: "留下", pos: "Verb", sentenceKr: "음식을 남겼어요.", sentenceMeaning: "Left food behind." },
        { kr: "남녀", en: "Men and women", zh: "男女", pos: "Noun", sentenceKr: "남녀 평등이 중요해요.", sentenceMeaning: "Gender equality is important." },
        { kr: "남다", en: "To remain", zh: "剩下", pos: "Verb", sentenceKr: "시간이 남았어요.", sentenceMeaning: "Time remains." },
        { kr: "남대문", en: "Namdaemun", zh: "南大门", pos: "Noun", sentenceKr: "남대문에 가요.", sentenceMeaning: "Go to Namdaemun." },
        { kr: "남동생", en: "Younger brother", zh: "弟弟", pos: "Noun", sentenceKr: "남동생을 돌봐요.", sentenceMeaning: "Look after younger brother." },
        { kr: "남산", en: "Namsan", zh: "南山", pos: "Noun", sentenceKr: "남산 타워가 보여요.", sentenceMeaning: "I can see Namsan Tower." },
        { kr: "남성", en: "Male", zh: "男性", pos: "Noun", sentenceKr: "남성 의류예요.", sentenceMeaning: "It's male clothing." },
        { kr: "남자", en: "Man", zh: "男人", pos: "Noun", sentenceKr: "남자와 여자.", sentenceMeaning: "Man and woman." },
        { kr: "남쪽", en: "South", zh: "南边", pos: "Noun", sentenceKr: "남쪽으로 가요.", sentenceMeaning: "Go south." },
        { kr: "남편", en: "Husband", zh: "丈夫", pos: "Noun", sentenceKr: "남편과 아내.", sentenceMeaning: "Husband and wife." },
        { kr: "낮", en: "Daytime", zh: "白天", pos: "Noun", sentenceKr: "낮에는 일해요.", sentenceMeaning: "I work during the day." },
        { kr: "낮다", en: "To be low", zh: "低", pos: "Adjective", sentenceKr: "산이 낮아요.", sentenceMeaning: "The mountain is low." },
        { kr: "낮잠", en: "Nap", zh: "午睡", pos: "Noun", sentenceKr: "낮잠을 자요.", sentenceMeaning: "Take a nap." },
        { kr: "내", en: "My", zh: "我的", pos: "Pronoun", sentenceKr: "내 가방이에요.", sentenceMeaning: "It is my bag." },
        { kr: "내과", en: "Internal medicine", zh: "内科", pos: "Noun", sentenceKr: "내과에 가요.", sentenceMeaning: "Go to internal medicine." },
        { kr: "내년", en: "Next year", zh: "明年", pos: "Noun", sentenceKr: "내년에 만나요.", sentenceMeaning: "Let's meet next year." },
        { kr: "내다", en: "To pay/submit", zh: "付/交", pos: "Verb", sentenceKr: "돈을 내요.", sentenceMeaning: "Pay money." },
        { kr: "내려가다", en: "To go down", zh: "下去", pos: "Verb", sentenceKr: "아래로 내려가요.", sentenceMeaning: "Go down." },
        { kr: "내려오다", en: "To come down", zh: "下来", pos: "Verb", sentenceKr: "밑으로 내려와요.", sentenceMeaning: "Come down." }
    ]
};
