const { MsEdgeTTS, OUTPUT_FORMAT } = require('msedge-tts');
const fs = require('fs');
const path = require('path');

const tsData = fs.readFileSync('src/lib/vocabulary-data.ts', 'utf-8');
const match = tsData.match(/(export\s+const\s+MOCK_VOCABULARY(?::\s*Record<string,\s*Word\[\]>)?\s*=\s*)(\{[\s\S]*?\});/);
const MOCK_VOCABULARY = eval('(' + match[2] + ')');

const sentencesDir = 'public/audio/sentences';

async function run() {
    const tasks = [];
    
    for (const cycle in MOCK_VOCABULARY) {
        for (const word of MOCK_VOCABULARY[cycle]) {
            if (word.sentenceKr) {
                const safeName = word.kr.replace(/[<>:"/\\|?*]/g, '');
                const sentenceFile = path.join(sentencesDir, `${safeName}.mp3`);
                tasks.push({
                    word: word.kr,
                    sentence: word.sentenceKr,
                    dest: sentenceFile
                });
            }
        }
    }

    console.log(`Total sentences to regenerate: ${tasks.length}`);

    const concurrency = 4;
    let activeIndex = 0;
    let completedCount = 0;

    async function worker(workerId) {
        const tts = new MsEdgeTTS();
        await tts.setMetadata("ko-KR-SunHiNeural", OUTPUT_FORMAT.AUDIO_24KHZ_48KBITRATE_MONO_MP3);

        const workerDir = path.join(__dirname, `worker_${workerId}`);
        if (!fs.existsSync(workerDir)) {
            fs.mkdirSync(workerDir, { recursive: true });
        }

        while (true) {
            const currentIdx = activeIndex++;
            if (currentIdx >= tasks.length) break;

            const task = tasks[currentIdx];
            // The file generated by msedge-tts is always named audio.mp3 in the directory passed
            const tempFilePath = path.join(workerDir, 'audio.mp3');

            try {
                // Generate TTS to the worker's isolated directory
                await tts.toFile(workerDir, task.sentence);
                
                // Copy to public/audio/sentences
                if (fs.existsSync(tempFilePath)) {
                    fs.copyFileSync(tempFilePath, task.dest);
                    fs.unlinkSync(tempFilePath);
                } else {
                    throw new Error("TTS generated file not found at " + tempFilePath);
                }
                
                completedCount++;
                if (completedCount % 50 === 0 || task.word === '간단히') {
                    console.log(`[Worker ${workerId}] Completed ${completedCount}/${tasks.length}: "${task.word}" -> "${task.sentence}"`);
                }
            } catch (e) {
                console.error(`[Worker ${workerId}] Failed for "${task.word}" (${task.sentence}):`, e.message);
                if (fs.existsSync(tempFilePath)) {
                    try { fs.unlinkSync(tempFilePath); } catch(_) {}
                }
            }

            // Brief delay between requests to be polite to the TTS server
            await new Promise(resolve => setTimeout(resolve, 250));
        }

        // Clean up worker directory
        try {
            fs.rmdirSync(workerDir);
        } catch(_) {}
    }

    console.log(`Starting regeneration with ${concurrency} parallel workers...`);
    const startTime = Date.now();
    await Promise.all(Array.from({ length: concurrency }, (_, i) => worker(i + 1)));
    const duration = ((Date.now() - startTime) / 1000).toFixed(1);
    console.log(`All TTS sentence audios regenerated in ${duration}s!`);
}

run().catch(console.error);
